imrpove script

diff --git a/tools/aml2raw b/tools/aml2raw
--- a/tools/aml2raw
+++ b/tools/aml2raw
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 ## hyphop ##
 
@@ -44,6 +44,9 @@ EXAMPLES:
 
 	# raw image output to file + compression detected from output name extension (img)
 	aml2raw ../img/Android_Pie.VIM3/dl/VIM3_Pie_V201112.7z ../img/VIM3_Pie_V201112.img
+
+	# atv images from SC convert example
+	./aml2raw SC_VIM3L_USER_ATV-v3.0-20201125.7z VIM3L-Android-TV-v3.0-20201125.raw.img.xz
 
 "
 }
@@ -134,6 +137,23 @@ curl -jkL -C- -o "$c" \
 
 }
 
+
+chk_z(){
+b=xze
+o="$TMP/bin/$b"
+
+[ "$xze" ] || \
+xze=$(which $b)
+[ $? = 0 ] && return
+
+MSG "[i] download $b"
+curl -jkL -C- -o "$o" \
+    https://raw.githubusercontent.com/krescue/krescue/master/tools/xze
+
+[ -x "$o" ] || \
+    chmod 0777 "$o"
+
+}
 SETUP(){
     CMD="sudo apt-get install $REQUIRED"
     MSG "[i] setup need root privs for next command"
@@ -158,6 +178,8 @@ IN=$1
 }
 [ -e "$IN" ] || DIE "not found $IN"
 
+[ "$2" ] && CO="$(realpath "$2")"
+
 [ "$TMP" ] || \
 TMP=/tmp/${0##*/}
 
@@ -169,13 +191,19 @@ MSG "[i] TMP: $TMP"
 
 O="$TMP"/update.img
 
+INF=${IN%.*}
+
 while [ ! -d "$IN" ]; do
 
 case $(file "$IN") in
     *7-zip*)
+    O=${IN%.*}.amlimage
     MSG "[i] 7z unpack $IN"
+    [ -e "$IN.unpacked" ] || {
     chk_a
-    $bsdtar -O -xf "$IN" '*.img' > "$O"  || DIE "unpack $IN"
+    $bsdtar -O -xf "$IN" '*.img' | dd conv=sparse status=progress of="$O"  || DIE "unpack $IN"
+    date > "$IN.unpacked"
+    }
     IN=$O
     ;;
     *)
@@ -187,7 +215,6 @@ case $(file "$IN") in
     head -c4096 "$IN" | grep -q PARTITION || DIE "unknown input $IN"
     $aml_image_v2_packer -d "$IN" "$D" 1>&2 || DIE "aml unpack $IN"
     cd $D
-
 
     break
 esac
@@ -240,6 +267,30 @@ INPUT="$dtc -q $DTB"
 $INPUT 1>/dev/null || DIE "dtb broken $DTB"
 }
 
+#INPUT="
+BOARD_=$($dtc -q $DTB | grep "\"khadas, " )
+
+case $BOARD_ in
+    *vim3l*|*VIM3L*)
+    BOARD=VIM3L
+    ;;
+    *vim2*|*VIM2*)
+    BOARD=VIM2
+    ;;
+    *vim3*|*VIM3*)
+    BOARD=VIM3
+    ;;
+    *vim*|*VIM*)
+    BOARD=VIM1
+    ;;
+    *)
+    DIE "unknown board $BOARD_"
+    exit 1
+esac
+#"
+
+MSG "[i] BOARD $BOARD"
+
 [ "$DTS" ] && \
 INPUT="cat $DTS"
 
@@ -250,7 +301,6 @@ mkdir -p $T
 MSG "[i] $P"
 
 # extract parition info !!! NOTE not super solution
-
 
 $INPUT | \
 grep -m1 partitions -A200 | \
@@ -313,8 +363,6 @@ CMP() {
     CT=zst
 
 RO=$T/image
-
-[ "$2" ] && CO="$2"
 
 [ "$CO" ] || {
     CO=$RO.$CT
@@ -392,15 +440,24 @@ while read l ; do
 	printf "[i] %10s %10x %10x %10x\n" $pname $b $size $o >&2
 	
 	PD=/dev/zero
+	PART_TYPE=$(file $P)
+	MSG "> $PART_TYPE"
 	[ -s $P ] && {
-	case $(file $P) in
+	case $PART_TYPE in
 	    *sparse*)
 	    PD=$P.raw
 	    CMD simg2img "$P" "$PD"
 	    ls -l1 "$P" "$PD" >&2
 	    ;;
+	    *buildvariant=*)
+	    LABEL=Android-TV
+	    BUILDER=SC
+	    MSG "[i] BOARD $BOARD => $LABEL+$BUILDER || PTYPE: $PTYPE // $INF"
+	    PD="$P"
+	    ;;
 	    *)
 	    PD="$P"
+	    ;;
 	esac
 	}
 	PART_OFFSET=$((o+BC))
@@ -430,6 +487,61 @@ case $CO in
     *)
     ls -l1 $CO >&2
 esac
+
+[ "$PTYPE" ] || \
+PTYPE=android
+
+[ "$LABEL" ] || \
+LABEL=android
+
+[ "$BOARD" ] || \
+BOARD=VIMx
+
+[ "$BUILDER" ] || \
+BUILDER=Khadas
+
+MSG "[i] BOARD $BOARD => $LABEL+$BUILDER || PTYPE: $PTYPE // $INF"
+
+case $CO in
+    *.xz)
+
+    chk_z
+    chk_z
+
+    case $PTYPE in
+
+    linux)
+    MSG "[i] compress xze :: $INF"
+    $xze $CO -9 --meta \
+    BOARD=BOARD \
+    LABEL=Linux \
+    BUILDER=Khadas \
+    LINK=http://dl.khadas.com \
+    DESC="linux $INF for Khadas EDGE board" \
+    || DIE "xze fail"
+
+    ;;
+    *)
+    $xze $CO -9 --meta \
+    BOARD=$BOARD \
+    LABEL=$LABEL \
+    BUILDER=$BUILDER \
+    LINK=http://dl.khadas.com \
+    DESC="$LABEL $INF for Khadas $BOARD board" \
+    || DIE "xze fail"
+    ;;
+
+    esac
+
+    rm -f $O
+
+    ;;
+
+esac
+
+exit
+
+
 
 exit 0
 
